openapi: 3.0.3
info:
  title: Suture Analysis API
  description: |
    REST API for YOLO-based suture analysis including detailed stitch measurements, suture classifications, advanced image preprocessing, robust detection methods, pixel-to-mm conversions, and complete error handling.
  version: 2.0.0
servers:
  - url: https://api.yolosuture.com/v1
    description: Production server
  - url: https://api.yolosuture.com/v1-beta
    description: Beta server
  - url: https://api.yolosuture.com/v1-alpha
    description: Alpha server

paths:

  /predict_suture_quality:
    post:
      summary: Predict suture quality (good, tight, loose).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image:
                  type: string
                  description: Base64-encoded image (JPG, PNG).
      responses:
        "200":
          description: Quality prediction successful.
          content:
            application/json:
              schema:
                properties:
                  prediction: {type: string, enum: [good, tight, loose]}
                  confidence: {type: number}
        "400": {description: Invalid request}
        "413": {description: Image too large}
        "500": {description: Internal server error}

  /stitch_length_measurement:
    post:
      summary: Measure stitch lengths.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image: {type: string}
                scale_px_to_mm: {type: number}
      responses:
        "200":
          description: Stitch length measurements successful.
          content:
            application/json:
              schema:
                properties:
                  stitch_lengths_mm: {type: array, items: {type: number}}
                  average_length_mm: {type: number}
        "400": {description: Invalid scale or request}
        "500": {description: Error calculating lengths}

  /stitch_angle_analysis:
    post:
      summary: Analyze angles of stitches.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image: {type: string}
      responses:
        "200":
          description: Stitch angle analysis successful.
          content:
            application/json:
              schema:
                properties:
                  angles_degrees: {type: array, items: {type: number}}
                  average_angle: {type: number}
        "400": {description: Bounding box orientation error}
        "500": {description: Angle analysis server error}

  /tail_length_measurement:
    post:
      summary: Measure tail lengths.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image: {type: string}
      responses:
        "200":
          description: Tail length measurements successful.
          content:
            application/json:
              schema:
                properties:
                  tail_lengths_mm: {type: array, items: {type: number}}
                  missing_tail_count: {type: integer}
        "400": {description: Tail detection failure}
        "500": {description: Tail length calculation error}

  /suture_distance_measurement:
    post:
      summary: Calculate distances between sutures.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image: {type: string}
                scale_px_to_mm: {type: number}
      responses:
        "200":
          description: Suture distance calculation successful.
          content:
            application/json:
              schema:
                properties:
                  suture_distances_mm: {type: array, items: {type: number}}
                  average_distance_mm: {type: number}
        "400": {description: Invalid scale or request}
        "500": {description: Distance calculation error}

  /knot_incision_distance_measurement:
    post:
      summary: Measure distances from knots to incision.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                image: {type: string}
      responses:
        "200":
          description: Knot-to-incision distance measurement successful.
          content:
            application/json:
              schema:
                properties:
                  distances_mm: {type: array, items: {type: number}}
                  average_distance_mm: {type: number}
        "400": {description: Incision detection failed}
        "500": {description: Knot distance calculation error}

components:
  schemas:
    preprocessing_options:
      type: object
      properties:
        grayscale: {type: boolean, default: false}
        gaussian_blur: {type: boolean, default: false}
        contour_extraction: {type: boolean, default: false}
        edge_detection: {type: boolean, default: false}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

x-domain-specific-details:
  preprocessing-techniques:
    - Resize to 640x640 pixels
    - Aspect ratio preservation
    - Center cropping
    - Channel manipulation
    - CLAHE enhancement
    - Gaussian blur and bilateral filtering
    - Contour extraction, edge detection
  data-augmentation:
    - 90-degree rotation
    - 1% noise addition
    - HSV adjustments
  hyperparameter-tuning:
    - Learning rate: 0.005
    - Weight decay: 0.0001
    - IoU threshold: 0.25
    - Epochs: 100-300
    - Batch size: 16
  model-performance-metrics:
    - Precision, Recall, mAP, F1 Score
  pixel-to-mm-conversion:
    - Gaussian, Hough line transform
    - Scale calibration via labeled scales
  detection-methods:
    - YOLOv8 OBB
    - Non-Maximum Suppression (NMS)
  frontend-considerations:
    - Real-time visualization
    - Interactive UI adjustments
    - Manual overrides
    - Progress indicators
    - Visual error feedback
  future-improvements:
    - YOLO v10
    - Automatic scale detection
    - Artifact removal
    - Image sharpening