server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: true

database:
  host: "localhost"
  port: 5432
  name: "suture_analysis"
  user: "postgres"
  password: "postgres"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/api.log" 