# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/monitoring.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Metrics collection
metrics:
  collection_interval: 60  # seconds
  retention_period: 7  # days
  storage:
    type: "prometheus"  # or "influxdb"
    host: "localhost"
    port: 9090
    database: "suture_metrics"

# Performance monitoring
performance:
  cpu:
    threshold: 80  # percentage
    alert_interval: 300  # seconds
  memory:
    threshold: 85  # percentage
    alert_interval: 300  # seconds
  gpu:
    threshold: 90  # percentage
    alert_interval: 300  # seconds

# Error tracking
error_tracking:
  service: "sentry"  # or "rollbar"
  dsn: "your-sentry-dsn"
  environment: "production"
  sample_rate: 1.0
  traces_sample_rate: 0.1

# API monitoring
api:
  rate_limit:
    requests_per_minute: 60
    burst_size: 10
  health_check:
    interval: 30  # seconds
    timeout: 5  # seconds
  endpoints:
    - path: "/api/v1/health"
      method: "GET"
      expected_status: 200
    - path: "/api/v1/predict"
      method: "POST"
      expected_status: 200

# Alerting configuration
alerting:
  email:
    enabled: true
    smtp_host: "smtp.example.com"
    smtp_port: 587
    sender: "alerts@suture-analysis.com"
    recipients:
      - "admin@suture-analysis.com"
  slack:
    enabled: true
    webhook_url: "your-slack-webhook-url"
    channel: "#alerts"
  pagerduty:
    enabled: false
    service_key: "your-pagerduty-key"

# Model monitoring
model_monitoring:
  drift_detection:
    enabled: true
    window_size: 1000
    threshold: 0.1
  performance:
    metrics:
      - "accuracy"
      - "precision"
      - "recall"
      - "f1_score"
    evaluation_interval: 3600  # seconds
  data_quality:
    checks:
      - "missing_values"
      - "outliers"
      - "distribution_shift"
    interval: 86400  # seconds 